/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Catalogue",
    },
    {
      type: "category",
      label: "Test",
      items: [
        {
          type: "autogenerated",
          dirName: "test",
        },
      ],
    },
    {
      type: "category",
      label: "React",
      items: [
        {
          type: "autogenerated",
          dirName: "react",
        },
      ],
    },
    {
      type: "category",
      label: "TypeScript",
      items: [
        {
          type: "autogenerated",
          dirName: "typescript",
        },
      ],
    },
  ],
};

module.exports = sidebars;
